#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/script/RL/checkpoints/verl_grpo_dna_assemble_3500/qwen3_4b-instruct_gene3500_11_rp/global_step_100/actor --target_dir /path/demo/script/RL/checkpoints/verl_grpo_dna_assemble_3500/qwen3_4b-instruct_gene3500_11_rp/step_100_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_100_hg_gene2000_10_rp/global_step_320/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_100_hg_gene2000_10_rp/step_320_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/qwen3_1___7B_gene2000_10_rp/global_step_434/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/qwen3_1___7B_gene2000_10_rp/step_434_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_320_hg_gene2000_drop_original_rp/global_step_460/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_320_hg_gene2000_drop_original_rp/step_460_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_gene2000_copypaste_rp_v2/global_step_160/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_gene2000_copypaste_rp_v2/step_160_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_safe_lr_sched_v1/global_step_100/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_safe_lr_sched_v1/step_100_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_safe_lr_v3_kl_1_decay_70_clip_01_ent_0001/global_step_230/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_safe_lr_v3_kl_1_decay_70_clip_01_ent_0001/step_230_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v3_6_rewards_g3/global_step_240/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v3_6_rewards_g3/step_240_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v3_g3_c460_c/global_step_249/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v3_g3_c460_c/step_249_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/global_step_250/actor --target_dir /path/demo/checkpoints/step_250_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v6_target_curve/global_step_130/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v6_target_curve/step_130_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v5_equal_weight/global_step_210/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v5_equal_weight/step_210_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v5_batch_random/global_step_190/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v5_batch_random/step_190_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v5_target_curve/global_step_250/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_460_hg_grpo_copypaste_v5_target_curve/step_250_hg
#python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_210_ew_grpo_copypaste_v6_ew/global_step_250/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_210_ew_grpo_copypaste_v6_ew/step_250_hg
# python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v7_ew/global_step_240/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v7_ew/step_240_hg
# python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v8_tc/global_step_250/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v8_tc/step_250_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v7_br/global_step_250/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v7_br/step_250_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v7_tc/global_step_250/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v7_tc/step_250_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v8_br/global_step_190/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v8_br/step_190_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v8_ew/global_step_250/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_grpo_copypaste_v8_ew/step_250_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_tc_grpo_copypaste_v7_br/global_step_150/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_tc_grpo_copypaste_v7_br/step_150_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_tc_grpo_copypaste_v7_tc/global_step_150/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_tc_grpo_copypaste_v7_tc/step_150_hg
python -m verl.model_merger merge  --backend fsdp  --local_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_tc_grpo_copypaste_v7_ew/global_step_150/actor --target_dir /path/demo/checkpoints/verl_grpo_dna_assemble_3500/step_250_ew_ew_tc_grpo_copypaste_v7_ew/step_150_hg